In [ ]:
import pandas as pd
import sqlite3

`import sqlite3` loads Python’s built-in library that allows Python to create, connect to, and interact with SQLite databases using SQL.

**When we write import sqlite3, we are telling Python:**

* I want to work with an SQLite database and run SQL queries from Python.

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/car_prices.csv")

conn = sqlite3.connect('data.db')
df.to_sql('car_prices', conn, if_exists='replace', index=False)

558837

I took a CSV file, loaded it into pandas, and then uploaded it into a database.
From now on, we stop using pandas and start asking questions with SQL

## **Establish a connection to the database.**

Before you can query any data, you must first connect your analysis environment to the database where the data lives.

**Why this is important**

* Databases do not respond to queries from nowhere

* A connection tells the database who is asking and from where

* All SQL queries are executed through an active connection

In [ ]:
conn = sqlite3.connect("data.db")

**`connect("data.db")`** → opens the database file

**`conn`** → the live communication channel

In [ ]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

         name
0  car_prices

Before we write queries, we always check which tables exist and what’s inside them.
* It’s the same as opening a CSV to see what columns you have


**`pd.read_sql_query(...)`**
* This is a pandas function.

* It allows you to run an SQL query directly from Python and get the result as a DataFrame.

1. **SELECT + FROM – get specific columns**

In [ ]:
pd.read_sql_query(
    "SELECT * FROM car_prices LIMIT 5;",
    conn
)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

`SELECT * FROM car_prices` → We want all the columns from the table called car_prices.

`*` just means “everything.”

`LIMIT 5` → We only want to see the first 5 rows to get a quick look at the data.

In [ ]:
pd.read_sql_query(
    "SELECT make, model, sellingprice FROM car_prices LIMIT 10;",
    conn
)

        make                model  sellingprice
0        Kia              Sorento       21500.0
1        Kia              Sorento       21500.0
2        BMW             3 Series       30000.0
3      Volvo                  S60       27750.0
4        BMW  6 Series Gran Coupe       67000.0
5     Nissan               Altima       10900.0
6        BMW                   M5       65000.0
7  Chevrolet                Cruze        9800.0
8       Audi                   A4       32250.0
9  Chevrolet               Camaro       17500.0

**2. WHERE – filter rows**

In [ ]:
pd.read_sql_query(
    "SELECT make, model, sellingprice FROM car_prices WHERE sellingprice > 30000 LIMIT 5;",
    conn
)

   make                model  sellingprice
0   BMW  6 Series Gran Coupe       67000.0
1   BMW                   M5       65000.0
2  Audi                   A4       32250.0
3  Audi                   A6       49750.0
4  Audi                   Q5       40000.0

**3. ORDER BY – sort results**

In [ ]:
pd.read_sql_query(
    "SELECT make, model, sellingprice FROM car_prices ORDER BY sellingprice DESC LIMIT 5;",
    conn
)

            make       model  sellingprice
0           Ford      Escape      230000.0
1        Ferrari  458 Italia      183000.0
2  Mercedes-Benz     S-Class      173000.0
3    Rolls-Royce       Ghost      171500.0
4    Rolls-Royce       Ghost      169500.0

**4. DISTINCT – unique values**

Show all unique car brands.

In [ ]:
pd.read_sql_query(
    "SELECT DISTINCT make FROM car_prices;",
    conn
)

            make
0            Kia
1            BMW
2          Volvo
3         Nissan
4      Chevrolet
..           ...
92           dot
93  Aston Martin
94        Fisker
95   Lamborghini
96         Lotus

[97 rows x 1 columns]

**5. COUNT() – count rows**

Count how many cars are in the table.

In [ ]:
pd.read_sql_query(
    "SELECT COUNT(*) AS total_cars FROM car_prices;",
    conn
)

   total_cars
0      558837

**6. SUM(), AVG(), MIN(), MAX() – aggregate functions**

In [ ]:
pd.read_sql_query(
    "SELECT SUM(sellingprice) AS total_price FROM car_prices;",
    conn
  )

    total_price
0  7.606368e+09

In [ ]:
pd.read_sql_query(
    "SELECT AVG(sellingprice) AS avg_price FROM car_prices;",
    conn
  )

     avg_price
0  13611.35881

In [ ]:
pd.read_sql_query(
    "SELECT MIN(sellingprice) AS cheapest_car FROM car_prices;",
    conn
  )

   cheapest_car
0           1.0

In [ ]:
pd.read_sql_query(
    "SELECT MAX(sellingprice) AS most_expensive_car FROM car_prices;",
    conn
  )

   most_expensive_car
0            230000.0

**7. GROUP BY + AVG() – aggregate by category**

In [ ]:
pd.read_sql_query(
    """
    SELECT make, AVG(sellingprice) AS avg_price
    FROM car_prices
    GROUP BY make
    ORDER BY avg_price DESC
    LIMIT 5;
    """,
    conn
)

          make      avg_price
0  Rolls-Royce  153488.235294
1      Ferrari  127210.526316
2  Lamborghini  112625.000000
3      Bentley   74367.672414
4    airstream   71000.000000

**8. Combined  filter, group, and sort**

In [ ]:
df_1 = pd.read_sql_query(
    """
    SELECT make, model, AVG(sellingprice) AS avg_price
    FROM car_prices
    WHERE year >= 2015
    GROUP BY make, model
    ORDER BY avg_price DESC
    LIMIT 10;
    """,
    conn
)
print(df_1)

            make              model      avg_price
0  Mercedes-Benz            G-Class  139750.000000
1            BMW                 M6  101333.333333
2  Mercedes-Benz            S-Class   99233.333333
3         Jaguar             F-TYPE   83425.000000
4         Nissan               GT-R   80274.000000
5            BMW               None   79633.333333
6          Lexus             LX 570   79500.000000
7     Land Rover  Range Rover Sport   77666.666667
8       Cadillac       Escalade ESV   74373.076923
9            BMW           6 Series   72625.000000

In [ ]:
df_1.head()

            make    model      avg_price
0  Mercedes-Benz  G-Class  139750.000000
1            BMW       M6  101333.333333
2  Mercedes-Benz  S-Class   99233.333333
3         Jaguar   F-TYPE   83425.000000
4         Nissan     GT-R   80274.000000

**Simple Subquery**

A subquery is simply: A query inside another query

it as:

* Ask one question, then use the answer to ask a better question.

In [ ]:
pd.read_sql_query(
    """
    SELECT make, model, sellingprice
    FROM car_prices
    WHERE sellingprice >
        (SELECT AVG(sellingprice) FROM car_prices);
    """,
    conn
)

         make                model  sellingprice
0         Kia              Sorento       21500.0
1         Kia              Sorento       21500.0
2         BMW             3 Series       30000.0
3       Volvo                  S60       27750.0
4         BMW  6 Series Gran Coupe       67000.0
...       ...                  ...           ...
234694    BMW             5 Series       22800.0
234695    Kia                 K900       33000.0
234696    Ram                 2500       30800.0
234697    BMW                   X5       34000.0
234698   Ford                F-150       26700.0

[234699 rows x 3 columns]

In [ ]:
pip install pymssql

Collecting pymssql
  Downloading pymssql-2.3.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (34 kB)
Downloading pymssql-2.3.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 9.3 MB/s eta 0:00:00
Installing collected packages: pymssql
Successfully installed pymssql-2.3.11

In [ ]:
import pymssql

In [ ]:
conn = pymssql.connect(
 server="2.tcp.eu.ngrok.io",
 port=12426,
 user="Hartz",
 password='StrongPassword123!',
 database="stock",
)

OperationalError: (18456, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (2.tcp.eu.ngrok.io)\nNet-Lib error during Connection refused (111)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (2.tcp.eu.ngrok.io)\nNet-Lib error during Connection refused (111)\n')

In [ ]:
query = "SELECT * FROM dbo.AAPL"
df2 = pd.read_sql(query, con=conn)

/tmp/ipython-input-2561497044.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(query, con=conn)

DatabaseError: Execution failed on sql: SELECT * FROM dbo.AAPL
Not connected to any MS SQL server
unable to rollback

In [ ]:
df2.head()

        date     open    high     low   close      volume
0 2026-01-09  259.075  260.21  256.22  259.37  39996967.0
1 2026-01-08  257.020  259.29  255.70  259.04  50419337.0
2 2026-01-07  263.200  263.68  259.81  260.33  48309804.0
3 2026-01-06  267.000  267.55  262.12  262.36  52352090.0
4 2026-01-05  270.640  271.51  266.14  267.26  45647190.0

In [ ]:
pd.read_sql(
    "SELECT * FROM dbo.AAPL;",
    conn
    )

/tmp/ipython-input-3868793186.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(

DatabaseError: Execution failed on sql: SELECT * FROM dbo.AAPL;
Not connected to any MS SQL server
unable to rollback

In [ ]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)